<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

	<PackageId>DataIngestorService.Contracts</PackageId>
	<Version>1.0.2</Version>
	<Authors>DarPers</Authors>
	<Company>DarPersCorporation</Company>
	<Description>Message contracts</Description>
	<PackageTags>dotnet;cool;library</PackageTags>
	<PackageLicenseExpression>MIT</PackageLicenseExpression>

	<RepositoryUrl>https://github.com/DarPers/WeakAppSolution</RepositoryUrl>
	<RepositoryType>git</RepositoryType>

	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
